// app/questions.js

export const learningModules = {
  tall_short: [
    { q: "Which one is TALL?",  a: { txt: "Giraffe", icon: "🦒" }, b: { txt: "Duck", icon: "🦆" }, correct: 'a' },
    { q: "Which one is SHORT?", a: { txt: "Tree", icon: "🌲" },   b: { txt: "Flower", icon: "🌻" }, correct: 'b' },
    { q: "Which one is TALL?",  a: { txt: "Building", icon: "🏢" }, b: { txt: "House", icon: "🏠" }, correct: 'a' },
    { q: "Which one is SHORT?", a: { txt: "Ladder", icon: "🪜" },  b: { txt: "Stool", icon: "🪑" }, correct: 'b' },
    { q: "Which one is TALL?",  a: { txt: "Mountain", icon: "🏔️" }, b: { txt: "Hill", icon: "⛰️" }, correct: 'a' },
    { q: "Which one is SHORT?", a: { txt: "Adult", icon: "👨" },   b: { txt: "Baby", icon: "👶" }, correct: 'b' },
    { q: "Which one is TALL?",  a: { txt: "Tower", icon: "🗼" },   b: { txt: "Tent", icon: "⛺" }, correct: 'a' },
  ],
  big_small: [
    { q: "Which one is BIG?",   a: { txt: "Elephant", icon: "🐘" }, b: { txt: "Ant", icon: "🐜" }, correct: 'a' },
    { q: "Which one is SMALL?", a: { txt: "Whale", icon: "🐋" },   b: { txt: "Fish", icon: "🐠" }, correct: 'b' },
    { q: "Which one is BIG?",   a: { txt: "Bus", icon: "🚌" },      b: { txt: "Car", icon: "🚗" }, correct: 'a' },
    { q: "Which one is SMALL?", a: { txt: "Watermelon", icon: "🍉" }, b: { txt: "Grape", icon: "🍇" }, correct: 'b' },
    { q: "Which one is BIG?",   a: { txt: "Earth", icon: "🌍" },    b: { txt: "Moon", icon: "🌕" }, correct: 'a' },
    { q: "Which one is SMALL?", a: { txt: "Lion", icon: "🦁" },    b: { txt: "Mouse", icon: "🐭" }, correct: 'b' },
    { q: "Which one is BIG?",   a: { txt: "Truck", icon: "🚛" },    b: { txt: "Bike", icon: "🚲" }, correct: 'a' },
  ],
  fat_thin: [
    { q: "Which one is FAT (Chubby)?", a: { txt: "Pufferfish", icon: "🐡" }, b: { txt: "Worm", icon: "🪱" }, correct: 'a' },
    { q: "Which one is THIN?",       a: { txt: "Pumpkin", icon: "🎃" },    b: { txt: "Pencil", icon: "✏️" }, correct: 'b' },
    { q: "Which one is FAT?",        a: { txt: "Hippo", icon: "🦛" },      b: { txt: "Snake", icon: "🐍" }, correct: 'a' },
    { q: "Which one is THIN?",       a: { txt: "Tree Trunk", icon: "🪵" }, b: { txt: "Twig", icon: "🌿" }, correct: 'b' },
    { q: "Which one is FAT?",        a: { txt: "Pig", icon: "🐖" },        b: { txt: "Flamingo", icon: "🦩" }, correct: 'a' },
  ],
  more_less: [
    { q: "Which side has MORE?", a: { txt: "3 Cookies", icon: "🍪🍪🍪" }, b: { txt: "1 Cookie", icon: "🍪" }, correct: 'a' },
    { q: "Which side has LESS?", a: { txt: "4 Balloons", icon: "🎈🎈🎈🎈" }, b: { txt: "2 Balloons", icon: "🎈🎈" }, correct: 'b' },
    { q: "Which side has MORE?", a: { txt: "5 Stars", icon: "⭐⭐⭐⭐⭐" }, b: { txt: "2 Stars", icon: "⭐⭐" }, correct: 'a' },
    { q: "Which side has LESS?", a: { txt: "3 Apples", icon: "🍎🍎🍎" }, b: { txt: "1 Apple", icon: "🍎" }, correct: 'b' },
    { q: "Which side has MORE?", a: { txt: "Many Fish", icon: "🐟🐟🐟🐟" }, b: { txt: "One Fish", icon: "🐟" }, correct: 'a' },
  ],
  counting: [
    { q: "How many Apples?", display: "🍎🍎", a: { txt: "Two", icon: "2️⃣" }, b: { txt: "Five", icon: "5️⃣" }, correct: 'a' },
    { q: "How many Stars?",  display: "⭐⭐⭐", a: { txt: "One", icon: "1️⃣" }, b: { txt: "Three", icon: "3️⃣" }, correct: 'b' },
    { q: "How many Cars?",   display: "🚗", a: { txt: "One", icon: "1️⃣" }, b: { txt: "Four", icon: "4️⃣" }, correct: 'a' },
    { q: "How many Balls?",  display: "⚽⚽⚽⚽", a: { txt: "Two", icon: "2️⃣" }, b: { txt: "Four", icon: "4️⃣" }, correct: 'b' },
    { q: "How many Cats?",   display: "🐱🐱", a: { txt: "Two", icon: "2️⃣" }, b: { txt: "Six", icon: "6️⃣" }, correct: 'a' },
  ],
  // --- NEW CATEGORIES ---
  colors: [
    { q: "Touch the RED one", a: { txt: "Apple", icon: "🍎" }, b: { txt: "Leaf", icon: "🍃" }, correct: 'a' },
    { q: "Touch the BLUE one", a: { txt: "Sun", icon: "☀️" }, b: { txt: "Ocean", icon: "🌊" }, correct: 'b' },
    { q: "Touch the YELLOW one", a: { txt: "Banana", icon: "🍌" }, b: { txt: "Grapes", icon: "🍇" }, correct: 'a' },
    { q: "Touch the GREEN one", a: { txt: "Fire", icon: "🔥" }, b: { txt: "Turtle", icon: "🐢" }, correct: 'b' },
    { q: "Touch the ORANGE one", a: { txt: "Basketball", icon: "🏀" }, b: { txt: "Moon", icon: "🌕" }, correct: 'a' },
  ],
  fast_slow: [
    { q: "Which one is FAST?", a: { txt: "Rocket", icon: "🚀" }, b: { txt: "Snail", icon: "🐌" }, correct: 'a' },
    { q: "Which one is SLOW?", a: { txt: "Race Car", icon: "🏎️" }, b: { txt: "Turtle", icon: "🐢" }, correct: 'b' },
    { q: "Which one is FAST?", a: { txt: "Cheetah", icon: "🐆" }, b: { txt: "Sloth", icon: "🦥" }, correct: 'a' },
    { q: "Which one is SLOW?", a: { txt: "Plane", icon: "✈️" }, b: { txt: "Walking", icon: "🚶" }, correct: 'b' },
  ],
  hot_cold: [
    { q: "Which one is HOT?", a: { txt: "Fire", icon: "🔥" }, b: { txt: "Snowman", icon: "⛄" }, correct: 'a' },
    { q: "Which one is COLD?", a: { txt: "Soup", icon: "🍲" }, b: { txt: "Ice Cube", icon: "🧊" }, correct: 'b' },
    { q: "Which one is HOT?", a: { txt: "Sun", icon: "☀️" }, b: { txt: "Rain", icon: "🌧️" }, correct: 'a' },
    { q: "Which one is COLD?", a: { txt: "Volcano", icon: "🌋" }, b: { txt: "Ice Cream", icon: "🍦" }, correct: 'b' },
  ],
  superhero: [
    { q: "Which superhero can FLY?", a: { txt: "Superman", icon: "🦸" }, b: { txt: "Batman", icon: "🦇" }, correct: 'a' },
    { q: "Which superhero is STRONG?", a: { txt: "Spider-Man", icon: "🕷️" }, b: { txt: "Hulk", icon: "💪" }, correct: 'b' },
    { q: "Which superhero has a SHIELD?", a: { txt: "Captain America", icon: "🛡️" }, b: { txt: "Iron Man", icon: "🤖" }, correct: 'a' },
    { q: "Which superhero is FAST?", a: { txt: "Flash", icon: "⚡" }, b: { txt: "Wonder Woman", icon: "👸" }, correct: 'a' },
    { q: "Which superhero helps OTHERS?", a: { txt: "All Heroes", icon: "🌟" }, b: { txt: "Villain", icon: "😈" }, correct: 'a' },
    { q: "Which superhero has a CAPE?", a: { txt: "Superman", icon: "🦸" }, b: { txt: "Hulk", icon: "💪" }, correct: 'a' },
  ],
  math_numbers: [
    { q: "Listen! What number is this?", number: 1, display: "1️⃣", a: { txt: "One", icon: "1️⃣" }, b: { txt: "Two", icon: "2️⃣" }, correct: 'a', speakText: "One" },
    { q: "Listen! What number is this?", number: 2, display: "2️⃣", a: { txt: "Two", icon: "2️⃣" }, b: { txt: "Three", icon: "3️⃣" }, correct: 'a', speakText: "Two" },
    { q: "Listen! What number is this?", number: 3, display: "3️⃣", a: { txt: "Three", icon: "3️⃣" }, b: { txt: "Four", icon: "4️⃣" }, correct: 'a', speakText: "Three" },
    { q: "Listen! What number is this?", number: 4, display: "4️⃣", a: { txt: "Four", icon: "4️⃣" }, b: { txt: "Five", icon: "5️⃣" }, correct: 'a', speakText: "Four" },
    { q: "Listen! What number is this?", number: 5, display: "5️⃣", a: { txt: "Five", icon: "5️⃣" }, b: { txt: "Six", icon: "6️⃣" }, correct: 'a', speakText: "Five" },
    { q: "Listen! What number is this?", number: 6, display: "6️⃣", a: { txt: "Six", icon: "6️⃣" }, b: { txt: "Seven", icon: "7️⃣" }, correct: 'a', speakText: "Six" },
    { q: "Listen! What number is this?", number: 7, display: "7️⃣", a: { txt: "Seven", icon: "7️⃣" }, b: { txt: "Eight", icon: "8️⃣" }, correct: 'a', speakText: "Seven" },
    { q: "Listen! What number is this?", number: 8, display: "8️⃣", a: { txt: "Eight", icon: "8️⃣" }, b: { txt: "Nine", icon: "9️⃣" }, correct: 'a', speakText: "Eight" },
    { q: "Listen! What number is this?", number: 9, display: "9️⃣", a: { txt: "Nine", icon: "9️⃣" }, b: { txt: "Ten", icon: "🔟" }, correct: 'a', speakText: "Nine" },
    { q: "Listen! What number is this?", number: 10, display: "🔟", a: { txt: "Ten", icon: "🔟" }, b: { txt: "One", icon: "1️⃣" }, correct: 'a', speakText: "Ten" },
  ],
  alphabet: [
    { q: "Listen! What letter is this?", letter: "A", display: "A", a: { txt: "A", icon: "A" }, b: { txt: "B", icon: "B" }, correct: 'a', speakText: "A" },
    { q: "Listen! What letter is this?", letter: "B", display: "B", a: { txt: "B", icon: "B" }, b: { txt: "C", icon: "C" }, correct: 'a', speakText: "B" },
    { q: "Listen! What letter is this?", letter: "C", display: "C", a: { txt: "C", icon: "C" }, b: { txt: "D", icon: "D" }, correct: 'a', speakText: "C" },
    { q: "Listen! What letter is this?", letter: "D", display: "D", a: { txt: "D", icon: "D" }, b: { txt: "E", icon: "E" }, correct: 'a', speakText: "D" },
    { q: "Listen! What letter is this?", letter: "E", display: "E", a: { txt: "E", icon: "E" }, b: { txt: "F", icon: "F" }, correct: 'a', speakText: "E" },
    { q: "Listen! What letter is this?", letter: "F", display: "F", a: { txt: "F", icon: "F" }, b: { txt: "G", icon: "G" }, correct: 'a', speakText: "F" },
    { q: "Listen! What letter is this?", letter: "G", display: "G", a: { txt: "G", icon: "G" }, b: { txt: "H", icon: "H" }, correct: 'a', speakText: "G" },
    { q: "Listen! What letter is this?", letter: "H", display: "H", a: { txt: "H", icon: "H" }, b: { txt: "I", icon: "I" }, correct: 'a', speakText: "H" },
    { q: "Listen! What letter is this?", letter: "I", display: "I", a: { txt: "I", icon: "I" }, b: { txt: "J", icon: "J" }, correct: 'a', speakText: "I" },
    { q: "Listen! What letter is this?", letter: "J", display: "J", a: { txt: "J", icon: "J" }, b: { txt: "K", icon: "K" }, correct: 'a', speakText: "J" },
    { q: "Listen! What letter is this?", letter: "K", display: "K", a: { txt: "K", icon: "K" }, b: { txt: "L", icon: "L" }, correct: 'a', speakText: "K" },
    { q: "Listen! What letter is this?", letter: "L", display: "L", a: { txt: "L", icon: "L" }, b: { txt: "M", icon: "M" }, correct: 'a', speakText: "L" },
    { q: "Listen! What letter is this?", letter: "M", display: "M", a: { txt: "M", icon: "M" }, b: { txt: "N", icon: "N" }, correct: 'a', speakText: "M" },
    { q: "Listen! What letter is this?", letter: "N", display: "N", a: { txt: "N", icon: "N" }, b: { txt: "O", icon: "O" }, correct: 'a', speakText: "N" },
    { q: "Listen! What letter is this?", letter: "O", display: "O", a: { txt: "O", icon: "O" }, b: { txt: "P", icon: "P" }, correct: 'a', speakText: "O" },
    { q: "Listen! What letter is this?", letter: "P", display: "P", a: { txt: "P", icon: "P" }, b: { txt: "Q", icon: "Q" }, correct: 'a', speakText: "P" },
    { q: "Listen! What letter is this?", letter: "Q", display: "Q", a: { txt: "Q", icon: "Q" }, b: { txt: "R", icon: "R" }, correct: 'a', speakText: "Q" },
    { q: "Listen! What letter is this?", letter: "R", display: "R", a: { txt: "R", icon: "R" }, b: { txt: "S", icon: "S" }, correct: 'a', speakText: "R" },
    { q: "Listen! What letter is this?", letter: "S", display: "S", a: { txt: "S", icon: "S" }, b: { txt: "T", icon: "T" }, correct: 'a', speakText: "S" },
    { q: "Listen! What letter is this?", letter: "T", display: "T", a: { txt: "T", icon: "T" }, b: { txt: "U", icon: "U" }, correct: 'a', speakText: "T" },
    { q: "Listen! What letter is this?", letter: "U", display: "U", a: { txt: "U", icon: "U" }, b: { txt: "V", icon: "V" }, correct: 'a', speakText: "U" },
    { q: "Listen! What letter is this?", letter: "V", display: "V", a: { txt: "V", icon: "V" }, b: { txt: "W", icon: "W" }, correct: 'a', speakText: "V" },
    { q: "Listen! What letter is this?", letter: "W", display: "W", a: { txt: "W", icon: "W" }, b: { txt: "X", icon: "X" }, correct: 'a', speakText: "W" },
    { q: "Listen! What letter is this?", letter: "X", display: "X", a: { txt: "X", icon: "X" }, b: { txt: "Y", icon: "Y" }, correct: 'a', speakText: "X" },
    { q: "Listen! What letter is this?", letter: "Y", display: "Y", a: { txt: "Y", icon: "Y" }, b: { txt: "Z", icon: "Z" }, correct: 'a', speakText: "Y" },
    { q: "Listen! What letter is this?", letter: "Z", display: "Z", a: { txt: "Z", icon: "Z" }, b: { txt: "A", icon: "A" }, correct: 'a', speakText: "Z" },
  ]
};
