// app/questions.js

export const learningModules = {
  tall_short: [
    { q: "Which one is TALL?",  a: { txt: "Giraffe", icon: "🦒" }, b: { txt: "Duck", icon: "🦆" }, correct: 'a' },
    { q: "Which one is SHORT?", a: { txt: "Tree", icon: "🌲" },   b: { txt: "Flower", icon: "🌻" }, correct: 'b' },
    { q: "Which one is TALL?",  a: { txt: "Building", icon: "🏢" }, b: { txt: "House", icon: "🏠" }, correct: 'a' },
    { q: "Which one is SHORT?", a: { txt: "Ladder", icon: "🪜" },  b: { txt: "Stool", icon: "🪑" }, correct: 'b' },
    { q: "Which one is TALL?",  a: { txt: "Mountain", icon: "🏔️" }, b: { txt: "Hill", icon: "⛰️" }, correct: 'a' },
    { q: "Which one is SHORT?", a: { txt: "Adult", icon: "👨" },   b: { txt: "Baby", icon: "👶" }, correct: 'b' },
    { q: "Which one is TALL?",  a: { txt: "Tower", icon: "🗼" },   b: { txt: "Tent", icon: "⛺" }, correct: 'a' },
    { q: "Which one is SHORT?", a: { txt: "Giraffe", icon: "🦒" }, b: { txt: "Rabbit", icon: "🐰" }, correct: 'b' },
    { q: "Which one is TALL?",  a: { txt: "Skyscraper", icon: "🏗️" }, b: { txt: "Cottage", icon: "🏡" }, correct: 'a' },
    { q: "Which one is SHORT?", a: { txt: "Tree", icon: "🌳" },   b: { txt: "Grass", icon: "🌱" }, correct: 'b' },
    { q: "Which one is TALL?",  a: { txt: "Crane", icon: "🏗️" }, b: { txt: "Bench", icon: "🪑" }, correct: 'a' },
    { q: "Which one is SHORT?", a: { txt: "Elephant", icon: "🐘" }, b: { txt: "Ant", icon: "🐜" }, correct: 'b' },
    { q: "Which one is TALL?",  a: { txt: "Lighthouse", icon: "🗼" }, b: { txt: "Mailbox", icon: "📮" }, correct: 'a' },
    { q: "Which one is SHORT?", a: { txt: "Giraffe", icon: "🦒" }, b: { txt: "Penguin", icon: "🐧" }, correct: 'b' },
    { q: "Which one is TALL?",  a: { txt: "Redwood", icon: "🌲" }, b: { txt: "Bush", icon: "🌿" }, correct: 'a' },
  ],
  big_small: [
    { q: "Which one is BIG?",   a: { txt: "Elephant", icon: "🐘" }, b: { txt: "Ant", icon: "🐜" }, correct: 'a' },
    { q: "Which one is SMALL?", a: { txt: "Whale", icon: "🐋" },   b: { txt: "Fish", icon: "🐠" }, correct: 'b' },
    { q: "Which one is BIG?",   a: { txt: "Bus", icon: "🚌" },      b: { txt: "Car", icon: "🚗" }, correct: 'a' },
    { q: "Which one is SMALL?", a: { txt: "Watermelon", icon: "🍉" }, b: { txt: "Grape", icon: "🍇" }, correct: 'b' },
    { q: "Which one is BIG?",   a: { txt: "Earth", icon: "🌍" },    b: { txt: "Moon", icon: "🌕" }, correct: 'a' },
    { q: "Which one is SMALL?", a: { txt: "Lion", icon: "🦁" },    b: { txt: "Mouse", icon: "🐭" }, correct: 'b' },
    { q: "Which one is BIG?",   a: { txt: "Truck", icon: "🚛" },    b: { txt: "Bike", icon: "🚲" }, correct: 'a' },
    { q: "Which one is SMALL?", a: { txt: "Pumpkin", icon: "🎃" }, b: { txt: "Pea", icon: "🫛" }, correct: 'b' },
    { q: "Which one is BIG?",   a: { txt: "Airplane", icon: "✈️" }, b: { txt: "Helicopter", icon: "🚁" }, correct: 'a' },
    { q: "Which one is SMALL?", a: { txt: "Bear", icon: "🐻" },    b: { txt: "Bee", icon: "🐝" }, correct: 'b' },
    { q: "Which one is BIG?",   a: { txt: "Ship", icon: "🚢" },    b: { txt: "Boat", icon: "⛵" }, correct: 'a' },
    { q: "Which one is SMALL?", a: { txt: "Tree", icon: "🌳" },    b: { txt: "Seed", icon: "🌰" }, correct: 'b' },
    { q: "Which one is BIG?",   a: { txt: "Dinosaur", icon: "🦕" }, b: { txt: "Lizard", icon: "🦎" }, correct: 'a' },
    { q: "Which one is SMALL?", a: { txt: "House", icon: "🏠" },   b: { txt: "Toy House", icon: "🏘️" }, correct: 'b' },
    { q: "Which one is BIG?",   a: { txt: "Giant", icon: "👹" },   b: { txt: "Dwarf", icon: "🧙" }, correct: 'a' },
  ],
  fat_thin: [
    { q: "Which one is FAT (Chubby)?", a: { txt: "Pufferfish", icon: "🐡" }, b: { txt: "Worm", icon: "🪱" }, correct: 'a' },
    { q: "Which one is THIN?",       a: { txt: "Pumpkin", icon: "🎃" },    b: { txt: "Pencil", icon: "✏️" }, correct: 'b' },
    { q: "Which one is FAT?",        a: { txt: "Hippo", icon: "🦛" },      b: { txt: "Snake", icon: "🐍" }, correct: 'a' },
    { q: "Which one is THIN?",       a: { txt: "Tree Trunk", icon: "🪵" }, b: { txt: "Twig", icon: "🌿" }, correct: 'b' },
    { q: "Which one is FAT?",        a: { txt: "Pig", icon: "🐖" },        b: { txt: "Flamingo", icon: "🦩" }, correct: 'a' },
    { q: "Which one is THIN?",       a: { txt: "Log", icon: "🪵" },       b: { txt: "Stick", icon: "🪵" }, correct: 'b' },
    { q: "Which one is FAT?",        a: { txt: "Bear", icon: "🐻" },       b: { txt: "Snake", icon: "🐍" }, correct: 'a' },
    { q: "Which one is THIN?",       a: { txt: "Rope", icon: "🪢" },       b: { txt: "String", icon: "🧵" }, correct: 'b' },
    { q: "Which one is FAT?",        a: { txt: "Elephant", icon: "🐘" },   b: { txt: "Giraffe", icon: "🦒" }, correct: 'a' },
    { q: "Which one is THIN?",       a: { txt: "Pole", icon: "🏗️" },      b: { txt: "Wire", icon: "🔌" }, correct: 'b' },
    { q: "Which one is FAT?",        a: { txt: "Whale", icon: "🐋" },      b: { txt: "Eel", icon: "🐍" }, correct: 'a' },
    { q: "Which one is THIN?",       a: { txt: "Pencil", icon: "✏️" },     b: { txt: "Needle", icon: "🪡" }, correct: 'b' },
  ],
  more_less: [
    { q: "Which side has MORE?", a: { txt: "3 Cookies", icon: "🍪🍪🍪" }, b: { txt: "1 Cookie", icon: "🍪" }, correct: 'a' },
    { q: "Which side has LESS?", a: { txt: "4 Balloons", icon: "🎈🎈🎈🎈" }, b: { txt: "2 Balloons", icon: "🎈🎈" }, correct: 'b' },
    { q: "Which side has MORE?", a: { txt: "5 Stars", icon: "⭐⭐⭐⭐⭐" }, b: { txt: "2 Stars", icon: "⭐⭐" }, correct: 'a' },
    { q: "Which side has LESS?", a: { txt: "3 Apples", icon: "🍎🍎🍎" }, b: { txt: "1 Apple", icon: "🍎" }, correct: 'b' },
    { q: "Which side has MORE?", a: { txt: "Many Fish", icon: "🐟🐟🐟🐟" }, b: { txt: "One Fish", icon: "🐟" }, correct: 'a' },
    { q: "Which side has LESS?", a: { txt: "6 Balls", icon: "⚽⚽⚽⚽⚽⚽" }, b: { txt: "3 Balls", icon: "⚽⚽⚽" }, correct: 'b' },
    { q: "Which side has MORE?", a: { txt: "4 Cars", icon: "🚗🚗🚗🚗" }, b: { txt: "2 Cars", icon: "🚗🚗" }, correct: 'a' },
    { q: "Which side has LESS?", a: { txt: "5 Ducks", icon: "🦆🦆🦆🦆🦆" }, b: { txt: "2 Ducks", icon: "🦆🦆" }, correct: 'b' },
    { q: "Which side has MORE?", a: { txt: "7 Hearts", icon: "❤️❤️❤️❤️❤️❤️❤️" }, b: { txt: "3 Hearts", icon: "❤️❤️❤️" }, correct: 'a' },
    { q: "Which side has LESS?", a: { txt: "8 Flowers", icon: "🌸🌸🌸🌸🌸🌸🌸🌸" }, b: { txt: "4 Flowers", icon: "🌸🌸🌸🌸" }, correct: 'b' },
    { q: "Which side has MORE?", a: { txt: "6 Birds", icon: "🐦🐦🐦🐦🐦🐦" }, b: { txt: "2 Birds", icon: "🐦🐦" }, correct: 'a' },
    { q: "Which side has LESS?", a: { txt: "9 Buttons", icon: "🔘🔘🔘🔘🔘🔘🔘🔘🔘" }, b: { txt: "5 Buttons", icon: "🔘🔘🔘🔘🔘" }, correct: 'b' },
  ],
  counting: [
    { q: "How many fingers?", display: "👆", displayImage: "/hands/hand-1.png", a: { txt: "One", icon: "1️⃣" }, b: { txt: "Two", icon: "2️⃣" }, correct: 'a' },
    { q: "How many fingers?", display: "✌️", displayImage: "/hands/hand-2.png", a: { txt: "Two", icon: "2️⃣" }, b: { txt: "Three", icon: "3️⃣" }, correct: 'a' },
    { q: "How many fingers?", display: "🤟", displayImage: "/hands/hand-3.png", a: { txt: "Three", icon: "3️⃣" }, b: { txt: "Four", icon: "4️⃣" }, correct: 'a' },
    { q: "How many fingers?", display: "✋", displayImage: "/hands/hand-4.png", a: { txt: "Four", icon: "4️⃣" }, b: { txt: "Five", icon: "5️⃣" }, correct: 'a' },
    { q: "How many fingers?", display: "🖐️", displayImage: "/hands/hand-5.png", a: { txt: "Five", icon: "5️⃣" }, b: { txt: "Three", icon: "3️⃣" }, correct: 'a' },
    { q: "How many fingers?", display: "👆", displayImage: "/hands/hand-1.png", a: { txt: "One", icon: "1️⃣" }, b: { txt: "Four", icon: "4️⃣" }, correct: 'a' },
    { q: "How many fingers?", display: "✌️", displayImage: "/hands/hand-2.png", a: { txt: "Two", icon: "2️⃣" }, b: { txt: "Five", icon: "5️⃣" }, correct: 'a' },
    { q: "How many fingers?", display: "🤟", displayImage: "/hands/hand-3.png", a: { txt: "Three", icon: "3️⃣" }, b: { txt: "One", icon: "1️⃣" }, correct: 'a' },
    { q: "How many fingers?", display: "✋", displayImage: "/hands/hand-4.png", a: { txt: "Four", icon: "4️⃣" }, b: { txt: "Two", icon: "2️⃣" }, correct: 'a' },
    { q: "How many fingers?", display: "🖐️", displayImage: "/hands/hand-5.png", a: { txt: "Five", icon: "5️⃣" }, b: { txt: "Two", icon: "2️⃣" }, correct: 'a' },
    { q: "How many fingers?", display: "👆", displayImage: "/hands/hand-1.png", a: { txt: "One", icon: "1️⃣" }, b: { txt: "Three", icon: "3️⃣" }, correct: 'a' },
    { q: "How many fingers?", display: "✌️", displayImage: "/hands/hand-2.png", a: { txt: "Two", icon: "2️⃣" }, b: { txt: "Four", icon: "4️⃣" }, correct: 'a' },
  ],
  colors: [
    { q: "Touch the RED one", a: { txt: "Apple", icon: "🍎" }, b: { txt: "Leaf", icon: "🍃" }, correct: 'a' },
    { q: "Touch the BLUE one", a: { txt: "Sun", icon: "☀️" }, b: { txt: "Ocean", icon: "🌊" }, correct: 'b' },
    { q: "Touch the YELLOW one", a: { txt: "Banana", icon: "🍌" }, b: { txt: "Grapes", icon: "🍇" }, correct: 'a' },
    { q: "Touch the GREEN one", a: { txt: "Fire", icon: "🔥" }, b: { txt: "Turtle", icon: "🐢" }, correct: 'b' },
    { q: "Touch the ORANGE one", a: { txt: "Basketball", icon: "🏀" }, b: { txt: "Moon", icon: "🌕" }, correct: 'a' },
    { q: "Touch the RED one", a: { txt: "Strawberry", icon: "🍓" }, b: { txt: "Blueberry", icon: "🫐" }, correct: 'a' },
    { q: "Touch the BLUE one", a: { txt: "Sky", icon: "☁️" }, b: { txt: "Sunset", icon: "🌅" }, correct: 'a' },
    { q: "Touch the YELLOW one", a: { txt: "Sun", icon: "☀️" }, b: { txt: "Moon", icon: "🌙" }, correct: 'a' },
    { q: "Touch the GREEN one", a: { txt: "Grass", icon: "🌱" }, b: { txt: "Fire", icon: "🔥" }, correct: 'a' },
    { q: "Touch the PURPLE one", a: { txt: "Grape", icon: "🍇" }, b: { txt: "Apple", icon: "🍎" }, correct: 'a' },
    { q: "Touch the PINK one", a: { txt: "Pig", icon: "🐷" }, b: { txt: "Elephant", icon: "🐘" }, correct: 'a' },
    { q: "Touch the BROWN one", a: { txt: "Bear", icon: "🐻" }, b: { txt: "Polar Bear", icon: "🐻‍❄️" }, correct: 'a' },
  ],
  fast_slow: [
    { q: "Which one is FAST?", a: { txt: "Rocket", icon: "🚀" }, b: { txt: "Snail", icon: "🐌" }, correct: 'a' },
    { q: "Which one is SLOW?", a: { txt: "Race Car", icon: "🏎️" }, b: { txt: "Turtle", icon: "🐢" }, correct: 'b' },
    { q: "Which one is FAST?", a: { txt: "Cheetah", icon: "🐆" }, b: { txt: "Sloth", icon: "🦥" }, correct: 'a' },
    { q: "Which one is SLOW?", a: { txt: "Plane", icon: "✈️" }, b: { txt: "Walking", icon: "🚶" }, correct: 'b' },
    { q: "Which one is FAST?", a: { txt: "Falcon", icon: "🦅" }, b: { txt: "Snail", icon: "🐌" }, correct: 'a' },
    { q: "Which one is SLOW?", a: { txt: "Train", icon: "🚂" }, b: { txt: "Caterpillar", icon: "🐛" }, correct: 'b' },
    { q: "Which one is FAST?", a: { txt: "Motorcycle", icon: "🏍️" }, b: { txt: "Bicycle", icon: "🚲" }, correct: 'a' },
    { q: "Which one is SLOW?", a: { txt: "Jet", icon: "✈️" }, b: { txt: "Walking", icon: "🚶" }, correct: 'b' },
    { q: "Which one is FAST?", a: { txt: "Lightning", icon: "⚡" }, b: { txt: "Cloud", icon: "☁️" }, correct: 'a' },
    { q: "Which one is SLOW?", a: { txt: "Rocket", icon: "🚀" }, b: { txt: "Tortoise", icon: "🐢" }, correct: 'b' },
  ],
  hot_cold: [
    { q: "Which one is HOT?", a: { txt: "Fire", icon: "🔥" }, b: { txt: "Snowman", icon: "⛄" }, correct: 'a' },
    { q: "Which one is COLD?", a: { txt: "Soup", icon: "🍲" }, b: { txt: "Ice Cube", icon: "🧊" }, correct: 'b' },
    { q: "Which one is HOT?", a: { txt: "Sun", icon: "☀️" }, b: { txt: "Rain", icon: "🌧️" }, correct: 'a' },
    { q: "Which one is COLD?", a: { txt: "Volcano", icon: "🌋" }, b: { txt: "Ice Cream", icon: "🍦" }, correct: 'b' },
    { q: "Which one is HOT?", a: { txt: "Oven", icon: "🔥" }, b: { txt: "Freezer", icon: "🧊" }, correct: 'a' },
    { q: "Which one is COLD?", a: { txt: "Coffee", icon: "☕" }, b: { txt: "Snow", icon: "❄️" }, correct: 'b' },
    { q: "Which one is HOT?", a: { txt: "Lava", icon: "🌋" }, b: { txt: "Ice", icon: "🧊" }, correct: 'a' },
    { q: "Which one is COLD?", a: { txt: "Tea", icon: "🍵" }, b: { txt: "Popsicle", icon: "🍭" }, correct: 'b' },
    { q: "Which one is HOT?", a: { txt: "Desert", icon: "🏜️" }, b: { txt: "Arctic", icon: "🧊" }, correct: 'a' },
    { q: "Which one is COLD?", a: { txt: "Campfire", icon: "🔥" }, b: { txt: "Fridge", icon: "🧊" }, correct: 'b' },
  ],
  superhero: [
    { q: "Which superhero can FLY?", a: { txt: "Superman", imageUrl: "/superheroes/superman.png", icon: "🦸" }, b: { txt: "Batman", imageUrl: "/superheroes/batman.png", icon: "🦇" }, correct: 'a' },
    { q: "Which superhero is STRONG?", a: { txt: "Spider-Man", imageUrl: "/superheroes/spiderman.png", icon: "🕷️" }, b: { txt: "Hulk", imageUrl: "/superheroes/hulk.png", icon: "💪" }, correct: 'b' },
    { q: "Which superhero has a SHIELD?", a: { txt: "Captain America", imageUrl: "/superheroes/captain-america.png", icon: "🛡️" }, b: { txt: "Iron Man", imageUrl: "/superheroes/ironman.png", icon: "🤖" }, correct: 'a' },
    { q: "Which superhero is FAST?", a: { txt: "Flash", imageUrl: "/superheroes/flash.png", icon: "⚡" }, b: { txt: "Wonder Woman", imageUrl: "/superheroes/wonder-woman.png", icon: "👸" }, correct: 'a' },
    { q: "Which superhero helps OTHERS?", a: { txt: "All Heroes", icon: "🌟" }, b: { txt: "Villain", icon: "😈" }, correct: 'a' },
    { q: "Which superhero has a CAPE?", a: { txt: "Superman", imageUrl: "/superheroes/superman.png", icon: "🦸" }, b: { txt: "Hulk", imageUrl: "/superheroes/hulk.png", icon: "💪" }, correct: 'a' },
    { q: "Which superhero can CLIMB WALLS?", a: { txt: "Spider-Man", imageUrl: "/superheroes/spiderman.png", icon: "🕷️" }, b: { txt: "Batman", imageUrl: "/superheroes/batman.png", icon: "🦇" }, correct: 'a' },
    { q: "Which superhero is GREEN?", a: { txt: "Hulk", imageUrl: "/superheroes/hulk.png", icon: "💪" }, b: { txt: "Superman", imageUrl: "/superheroes/superman.png", icon: "🦸" }, correct: 'a' },
    { q: "Which superhero wears RED?", a: { txt: "Spider-Man", imageUrl: "/superheroes/spiderman.png", icon: "🕷️" }, b: { txt: "Batman", imageUrl: "/superheroes/batman.png", icon: "🦇" }, correct: 'a' },
    { q: "Which superhero is BRAVE?", a: { txt: "All Heroes", icon: "🦸" }, b: { txt: "Villain", icon: "😈" }, correct: 'a' },
    { q: "Which superhero has WEBS?", a: { txt: "Spider-Man", imageUrl: "/superheroes/spiderman.png", icon: "🕷️" }, b: { txt: "Batman", imageUrl: "/superheroes/batman.png", icon: "🦇" }, correct: 'a' },
    { q: "Which superhero is from KRYPTON?", a: { txt: "Superman", imageUrl: "/superheroes/superman.png", icon: "🦸" }, b: { txt: "Hulk", imageUrl: "/superheroes/hulk.png", icon: "💪" }, correct: 'a' },
  ],
  math_numbers: [
    { q: "Listen! What number is this?", number: 1, display: "1️⃣", a: { txt: "One", icon: "1️⃣" }, b: { txt: "Two", icon: "2️⃣" }, correct: 'a', speakText: "One" },
    { q: "Listen! What number is this?", number: 2, display: "2️⃣", a: { txt: "Two", icon: "2️⃣" }, b: { txt: "Three", icon: "3️⃣" }, correct: 'a', speakText: "Two" },
    { q: "Listen! What number is this?", number: 3, display: "3️⃣", a: { txt: "Three", icon: "3️⃣" }, b: { txt: "Four", icon: "4️⃣" }, correct: 'a', speakText: "Three" },
    { q: "Listen! What number is this?", number: 4, display: "4️⃣", a: { txt: "Four", icon: "4️⃣" }, b: { txt: "Five", icon: "5️⃣" }, correct: 'a', speakText: "Four" },
    { q: "Listen! What number is this?", number: 5, display: "5️⃣", a: { txt: "Five", icon: "5️⃣" }, b: { txt: "Six", icon: "6️⃣" }, correct: 'a', speakText: "Five" },
    { q: "Listen! What number is this?", number: 6, display: "6️⃣", a: { txt: "Six", icon: "6️⃣" }, b: { txt: "Seven", icon: "7️⃣" }, correct: 'a', speakText: "Six" },
    { q: "Listen! What number is this?", number: 7, display: "7️⃣", a: { txt: "Seven", icon: "7️⃣" }, b: { txt: "Eight", icon: "8️⃣" }, correct: 'a', speakText: "Seven" },
    { q: "Listen! What number is this?", number: 8, display: "8️⃣", a: { txt: "Eight", icon: "8️⃣" }, b: { txt: "Nine", icon: "9️⃣" }, correct: 'a', speakText: "Eight" },
    { q: "Listen! What number is this?", number: 9, display: "9️⃣", a: { txt: "Nine", icon: "9️⃣" }, b: { txt: "Ten", icon: "🔟" }, correct: 'a', speakText: "Nine" },
    { q: "Listen! What number is this?", number: 10, display: "🔟", a: { txt: "Ten", icon: "🔟" }, b: { txt: "One", icon: "1️⃣" }, correct: 'a', speakText: "Ten" },
    { q: "Listen! What number is this?", number: 1, display: "1️⃣", a: { txt: "One", icon: "1️⃣" }, b: { txt: "Three", icon: "3️⃣" }, correct: 'a', speakText: "One" },
    { q: "Listen! What number is this?", number: 2, display: "2️⃣", a: { txt: "Two", icon: "2️⃣" }, b: { txt: "Four", icon: "4️⃣" }, correct: 'a', speakText: "Two" },
    { q: "Listen! What number is this?", number: 3, display: "3️⃣", a: { txt: "Three", icon: "3️⃣" }, b: { txt: "Five", icon: "5️⃣" }, correct: 'a', speakText: "Three" },
    { q: "Listen! What number is this?", number: 4, display: "4️⃣", a: { txt: "Four", icon: "4️⃣" }, b: { txt: "Six", icon: "6️⃣" }, correct: 'a', speakText: "Four" },
    { q: "Listen! What number is this?", number: 5, display: "5️⃣", a: { txt: "Five", icon: "5️⃣" }, b: { txt: "Seven", icon: "7️⃣" }, correct: 'a', speakText: "Five" },
  ],
  alphabet: [
    { q: "Listen! What letter is this?", letter: "A", display: "A", a: { txt: "A", icon: "A" }, b: { txt: "B", icon: "B" }, correct: 'a', speakText: "A" },
    { q: "Listen! What letter is this?", letter: "B", display: "B", a: { txt: "B", icon: "B" }, b: { txt: "C", icon: "C" }, correct: 'a', speakText: "B" },
    { q: "Listen! What letter is this?", letter: "C", display: "C", a: { txt: "C", icon: "C" }, b: { txt: "D", icon: "D" }, correct: 'a', speakText: "C" },
    { q: "Listen! What letter is this?", letter: "D", display: "D", a: { txt: "D", icon: "D" }, b: { txt: "E", icon: "E" }, correct: 'a', speakText: "D" },
    { q: "Listen! What letter is this?", letter: "E", display: "E", a: { txt: "E", icon: "E" }, b: { txt: "F", icon: "F" }, correct: 'a', speakText: "E" },
    { q: "Listen! What letter is this?", letter: "F", display: "F", a: { txt: "F", icon: "F" }, b: { txt: "G", icon: "G" }, correct: 'a', speakText: "F" },
    { q: "Listen! What letter is this?", letter: "G", display: "G", a: { txt: "G", icon: "G" }, b: { txt: "H", icon: "H" }, correct: 'a', speakText: "G" },
    { q: "Listen! What letter is this?", letter: "H", display: "H", a: { txt: "H", icon: "H" }, b: { txt: "I", icon: "I" }, correct: 'a', speakText: "H" },
    { q: "Listen! What letter is this?", letter: "I", display: "I", a: { txt: "I", icon: "I" }, b: { txt: "J", icon: "J" }, correct: 'a', speakText: "I" },
    { q: "Listen! What letter is this?", letter: "J", display: "J", a: { txt: "J", icon: "J" }, b: { txt: "K", icon: "K" }, correct: 'a', speakText: "J" },
    { q: "Listen! What letter is this?", letter: "K", display: "K", a: { txt: "K", icon: "K" }, b: { txt: "L", icon: "L" }, correct: 'a', speakText: "K" },
    { q: "Listen! What letter is this?", letter: "L", display: "L", a: { txt: "L", icon: "L" }, b: { txt: "M", icon: "M" }, correct: 'a', speakText: "L" },
    { q: "Listen! What letter is this?", letter: "M", display: "M", a: { txt: "M", icon: "M" }, b: { txt: "N", icon: "N" }, correct: 'a', speakText: "M" },
    { q: "Listen! What letter is this?", letter: "N", display: "N", a: { txt: "N", icon: "N" }, b: { txt: "O", icon: "O" }, correct: 'a', speakText: "N" },
    { q: "Listen! What letter is this?", letter: "O", display: "O", a: { txt: "O", icon: "O" }, b: { txt: "P", icon: "P" }, correct: 'a', speakText: "O" },
    { q: "Listen! What letter is this?", letter: "P", display: "P", a: { txt: "P", icon: "P" }, b: { txt: "Q", icon: "Q" }, correct: 'a', speakText: "P" },
    { q: "Listen! What letter is this?", letter: "Q", display: "Q", a: { txt: "Q", icon: "Q" }, b: { txt: "R", icon: "R" }, correct: 'a', speakText: "Q" },
    { q: "Listen! What letter is this?", letter: "R", display: "R", a: { txt: "R", icon: "R" }, b: { txt: "S", icon: "S" }, correct: 'a', speakText: "R" },
    { q: "Listen! What letter is this?", letter: "S", display: "S", a: { txt: "S", icon: "S" }, b: { txt: "T", icon: "T" }, correct: 'a', speakText: "S" },
    { q: "Listen! What letter is this?", letter: "T", display: "T", a: { txt: "T", icon: "T" }, b: { txt: "U", icon: "U" }, correct: 'a', speakText: "T" },
    { q: "Listen! What letter is this?", letter: "U", display: "U", a: { txt: "U", icon: "U" }, b: { txt: "V", icon: "V" }, correct: 'a', speakText: "U" },
    { q: "Listen! What letter is this?", letter: "V", display: "V", a: { txt: "V", icon: "V" }, b: { txt: "W", icon: "W" }, correct: 'a', speakText: "V" },
    { q: "Listen! What letter is this?", letter: "W", display: "W", a: { txt: "W", icon: "W" }, b: { txt: "X", icon: "X" }, correct: 'a', speakText: "W" },
    { q: "Listen! What letter is this?", letter: "X", display: "X", a: { txt: "X", icon: "X" }, b: { txt: "Y", icon: "Y" }, correct: 'a', speakText: "X" },
    { q: "Listen! What letter is this?", letter: "Y", display: "Y", a: { txt: "Y", icon: "Y" }, b: { txt: "Z", icon: "Z" }, correct: 'a', speakText: "Y" },
    { q: "Listen! What letter is this?", letter: "Z", display: "Z", a: { txt: "Z", icon: "Z" }, b: { txt: "A", icon: "A" }, correct: 'a', speakText: "Z" },
    { q: "Listen! What letter is this?", letter: "A", display: "A", a: { txt: "A", icon: "A" }, b: { txt: "C", icon: "C" }, correct: 'a', speakText: "A" },
    { q: "Listen! What letter is this?", letter: "B", display: "B", a: { txt: "B", icon: "B" }, b: { txt: "D", icon: "D" }, correct: 'a', speakText: "B" },
    { q: "Listen! What letter is this?", letter: "C", display: "C", a: { txt: "C", icon: "C" }, b: { txt: "E", icon: "E" }, correct: 'a', speakText: "C" },
  ],
  shapes: [
    { q: "Which one is a CIRCLE?", a: { txt: "Circle", icon: "⭕" }, b: { txt: "Square", icon: "⬜" }, correct: 'a' },
    { q: "Which one is a SQUARE?", a: { txt: "Triangle", icon: "🔺" }, b: { txt: "Square", icon: "⬜" }, correct: 'b' },
    { q: "Which one is a TRIANGLE?", a: { txt: "Triangle", icon: "🔺" }, b: { txt: "Circle", icon: "⭕" }, correct: 'a' },
    { q: "Which one is a STAR?", a: { txt: "Star", icon: "⭐" }, b: { txt: "Circle", icon: "⭕" }, correct: 'a' },
    { q: "Which one is a HEART?", a: { txt: "Heart", icon: "❤️" }, b: { txt: "Square", icon: "⬜" }, correct: 'a' },
    { q: "Which one is ROUND?", a: { txt: "Circle", icon: "⭕" }, b: { txt: "Square", icon: "⬜" }, correct: 'a' },
    { q: "Which one has CORNERS?", a: { txt: "Square", icon: "⬜" }, b: { txt: "Circle", icon: "⭕" }, correct: 'a' },
    { q: "Which one is a DIAMOND?", a: { txt: "Diamond", icon: "💎" }, b: { txt: "Circle", icon: "⭕" }, correct: 'a' },
    { q: "Which one is a RECTANGLE?", a: { txt: "Rectangle", icon: "▭" }, b: { txt: "Circle", icon: "⭕" }, correct: 'a' },
    { q: "Which one is a CIRCLE?", a: { txt: "Circle", icon: "⭕" }, b: { txt: "Triangle", icon: "🔺" }, correct: 'a' },
  ],
  body_parts: [
    { q: "Touch your NOSE", a: { txt: "Nose", icon: "👃" }, b: { txt: "Ear", icon: "👂" }, correct: 'a' },
    { q: "Touch your EYES", a: { txt: "Eyes", icon: "👀" }, b: { txt: "Mouth", icon: "👄" }, correct: 'a' },
    { q: "Touch your EARS", a: { txt: "Hand", icon: "✋" }, b: { txt: "Ear", icon: "👂" }, correct: 'b' },
    { q: "Touch your MOUTH", a: { txt: "Mouth", icon: "👄" }, b: { txt: "Nose", icon: "👃" }, correct: 'a' },
    { q: "Touch your HANDS", a: { txt: "Hand", icon: "✋" }, b: { txt: "Foot", icon: "🦶" }, correct: 'a' },
    { q: "Touch your FEET", a: { txt: "Hand", icon: "✋" }, b: { txt: "Foot", icon: "🦶" }, correct: 'b' },
    { q: "Touch your HEAD", a: { txt: "Head", icon: "🧠" }, b: { txt: "Hand", icon: "✋" }, correct: 'a' },
    { q: "Touch your ARMS", a: { txt: "Arm", icon: "💪" }, b: { txt: "Leg", icon: "🦵" }, correct: 'a' },
    { q: "Touch your LEGS", a: { txt: "Arm", icon: "💪" }, b: { txt: "Leg", icon: "🦵" }, correct: 'b' },
    { q: "Touch your FINGERS", a: { txt: "Fingers", icon: "👆" }, b: { txt: "Toes", icon: "🦶" }, correct: 'a' },
  ],
  opposites: [
    { q: "Which one is UP?", a: { txt: "Up", icon: "⬆️" }, b: { txt: "Down", icon: "⬇️" }, correct: 'a' },
    { q: "Which one is DOWN?", a: { txt: "Up", icon: "⬆️" }, b: { txt: "Down", icon: "⬇️" }, correct: 'b' },
    { q: "Which one is IN?", a: { txt: "In", icon: "📥" }, b: { txt: "Out", icon: "📤" }, correct: 'a' },
    { q: "Which one is OUT?", a: { txt: "In", icon: "📥" }, b: { txt: "Out", icon: "📤" }, correct: 'b' },
    { q: "Which one is OPEN?", a: { txt: "Open", icon: "🔓" }, b: { txt: "Closed", icon: "🔒" }, correct: 'a' },
    { q: "Which one is CLOSED?", a: { txt: "Open", icon: "🔓" }, b: { txt: "Closed", icon: "🔒" }, correct: 'b' },
    { q: "Which one is DAY?", a: { txt: "Day", icon: "☀️" }, b: { txt: "Night", icon: "🌙" }, correct: 'a' },
    { q: "Which one is NIGHT?", a: { txt: "Day", icon: "☀️" }, b: { txt: "Night", icon: "🌙" }, correct: 'b' },
    { q: "Which one is ON?", a: { txt: "On", icon: "💡" }, b: { txt: "Off", icon: "🔌" }, correct: 'a' },
    { q: "Which one is OFF?", a: { txt: "On", icon: "💡" }, b: { txt: "Off", icon: "🔌" }, correct: 'b' },
    { q: "Which one is FULL?", a: { txt: "Full", icon: "🪣" }, b: { txt: "Empty", icon: "🪣" }, correct: 'a' },
    { q: "Which one is EMPTY?", a: { txt: "Full", icon: "🪣" }, b: { txt: "Empty", icon: "🪣" }, correct: 'b' },
  ],
  animals: [
    { q: "Which animal says MOO?", a: { txt: "Cow", icon: "🐄" }, b: { txt: "Dog", icon: "🐕" }, correct: 'a', sound: "moo" },
    { q: "Which animal says WOOF?", a: { txt: "Cat", icon: "🐱" }, b: { txt: "Dog", icon: "🐕" }, correct: 'b', sound: "woof" },
    { q: "Which animal says MEOW?", a: { txt: "Cat", icon: "🐱" }, b: { txt: "Duck", icon: "🦆" }, correct: 'a', sound: "meow" },
    { q: "Which animal says QUACK?", a: { txt: "Duck", icon: "🦆" }, b: { txt: "Chicken", icon: "🐔" }, correct: 'a', sound: "quack" },
    { q: "Which animal says ROAR?", a: { txt: "Lion", icon: "🦁" }, b: { txt: "Elephant", icon: "🐘" }, correct: 'a', sound: "roar" },
    { q: "Which animal says OINK?", a: { txt: "Pig", icon: "🐷" }, b: { txt: "Sheep", icon: "🐑" }, correct: 'a', sound: "oink" },
    { q: "Which animal says BAA?", a: { txt: "Cow", icon: "🐄" }, b: { txt: "Sheep", icon: "🐑" }, correct: 'b', sound: "baa" },
    { q: "Which animal says NEIGH?", a: { txt: "Horse", icon: "🐴" }, b: { txt: "Cow", icon: "🐄" }, correct: 'a', sound: "neigh" },
    { q: "Which animal FLIES?", a: { txt: "Bird", icon: "🐦" }, b: { txt: "Fish", icon: "🐠" }, correct: 'a' },
    { q: "Which animal SWIMS?", a: { txt: "Bird", icon: "🐦" }, b: { txt: "Fish", icon: "🐠" }, correct: 'b' },
  ],
  food: [
    { q: "Which one is a FRUIT?", a: { txt: "Apple", icon: "🍎" }, b: { txt: "Bread", icon: "🍞" }, correct: 'a' },
    { q: "Which one is a VEGETABLE?", a: { txt: "Carrot", icon: "🥕" }, b: { txt: "Banana", icon: "🍌" }, correct: 'a' },
    { q: "Which one is SWEET?", a: { txt: "Cake", icon: "🎂" }, b: { txt: "Broccoli", icon: "🥦" }, correct: 'a' },
    { q: "Which one is HEALTHY?", a: { txt: "Apple", icon: "🍎" }, b: { txt: "Candy", icon: "🍬" }, correct: 'a' },
    { q: "Which one is a FRUIT?", a: { txt: "Orange", icon: "🍊" }, b: { txt: "Carrot", icon: "🥕" }, correct: 'a' },
    { q: "Which one is a VEGETABLE?", a: { txt: "Tomato", icon: "🍅" }, b: { txt: "Strawberry", icon: "🍓" }, correct: 'a' },
    { q: "Which one is YELLOW?", a: { txt: "Banana", icon: "🍌" }, b: { txt: "Apple", icon: "🍎" }, correct: 'a' },
    { q: "Which one is RED?", a: { txt: "Apple", icon: "🍎" }, b: { txt: "Banana", icon: "🍌" }, correct: 'a' },
    { q: "Which one is ROUND?", a: { txt: "Orange", icon: "🍊" }, b: { txt: "Banana", icon: "🍌" }, correct: 'a' },
    { q: "Which one is a SNACK?", a: { txt: "Cookie", icon: "🍪" }, b: { txt: "Broccoli", icon: "🥦" }, correct: 'a' },
  ],
  transportation: [
    { q: "Which one FLIES?", a: { txt: "Airplane", icon: "✈️" }, b: { txt: "Car", icon: "🚗" }, correct: 'a' },
    { q: "Which one is on WATER?", a: { txt: "Boat", icon: "⛵" }, b: { txt: "Car", icon: "🚗" }, correct: 'a' },
    { q: "Which one has WHEELS?", a: { txt: "Bike", icon: "🚲" }, b: { txt: "Boat", icon: "⛵" }, correct: 'a' },
    { q: "Which one is FAST?", a: { txt: "Rocket", icon: "🚀" }, b: { txt: "Bike", icon: "🚲" }, correct: 'a' },
    { q: "Which one is SLOW?", a: { txt: "Rocket", icon: "🚀" }, b: { txt: "Bike", icon: "🚲" }, correct: 'b' },
    { q: "Which one CARRIES PEOPLE?", a: { txt: "Bus", icon: "🚌" }, b: { txt: "Truck", icon: "🚛" }, correct: 'a' },
    { q: "Which one is BIG?", a: { txt: "Truck", icon: "🚛" }, b: { txt: "Bike", icon: "🚲" }, correct: 'a' },
    { q: "Which one is SMALL?", a: { txt: "Car", icon: "🚗" }, b: { txt: "Bus", icon: "🚌" }, correct: 'a' },
    { q: "Which one goes CHOO CHOO?", a: { txt: "Train", icon: "🚂" }, b: { txt: "Car", icon: "🚗" }, correct: 'a' },
    { q: "Which one is in SPACE?", a: { txt: "Rocket", icon: "🚀" }, b: { txt: "Boat", icon: "⛵" }, correct: 'a' },
  ],
  emotions: [
    { q: "Which face is HAPPY?", a: { txt: "Happy", icon: "😊" }, b: { txt: "Sad", icon: "😢" }, correct: 'a' },
    { q: "Which face is SAD?", a: { txt: "Happy", icon: "😊" }, b: { txt: "Sad", icon: "😢" }, correct: 'b' },
    { q: "Which face is ANGRY?", a: { txt: "Angry", icon: "😠" }, b: { txt: "Happy", icon: "😊" }, correct: 'a' },
    { q: "Which face is SURPRISED?", a: { txt: "Surprised", icon: "😲" }, b: { txt: "Sleepy", icon: "😴" }, correct: 'a' },
    { q: "Which face is SLEEPY?", a: { txt: "Sleepy", icon: "😴" }, b: { txt: "Happy", icon: "😊" }, correct: 'a' },
    { q: "Which face is EXCITED?", a: { txt: "Excited", icon: "🤩" }, b: { txt: "Sad", icon: "😢" }, correct: 'a' },
    { q: "Which face is SCARED?", a: { txt: "Scared", icon: "😨" }, b: { txt: "Happy", icon: "😊" }, correct: 'a' },
    { q: "Which face is SILLY?", a: { txt: "Silly", icon: "🤪" }, b: { txt: "Sad", icon: "😢" }, correct: 'a' },
    { q: "Which face is HAPPY?", a: { txt: "Happy", icon: "😊" }, b: { txt: "Angry", icon: "😠" }, correct: 'a' },
    { q: "Which face is LOVING?", a: { txt: "Loving", icon: "🥰" }, b: { txt: "Sad", icon: "😢" }, correct: 'a' },
  ],
  weather: [
    { q: "Which one is SUNNY?", a: { txt: "Sun", icon: "☀️" }, b: { txt: "Rain", icon: "🌧️" }, correct: 'a' },
    { q: "Which one is RAINY?", a: { txt: "Sun", icon: "☀️" }, b: { txt: "Rain", icon: "🌧️" }, correct: 'b' },
    { q: "Which one is SNOWY?", a: { txt: "Snow", icon: "❄️" }, b: { txt: "Sun", icon: "☀️" }, correct: 'a' },
    { q: "Which one is CLOUDY?", a: { txt: "Cloud", icon: "☁️" }, b: { txt: "Sun", icon: "☀️" }, correct: 'a' },
    { q: "Which one is WINDY?", a: { txt: "Wind", icon: "💨" }, b: { txt: "Rain", icon: "🌧️" }, correct: 'a' },
    { q: "Which one is HOT?", a: { txt: "Sun", icon: "☀️" }, b: { txt: "Snow", icon: "❄️" }, correct: 'a' },
    { q: "Which one is COLD?", a: { txt: "Sun", icon: "☀️" }, b: { txt: "Snow", icon: "❄️" }, correct: 'b' },
    { q: "Which one is WET?", a: { txt: "Rain", icon: "🌧️" }, b: { txt: "Sun", icon: "☀️" }, correct: 'a' },
    { q: "Which one is BRIGHT?", a: { txt: "Sun", icon: "☀️" }, b: { txt: "Cloud", icon: "☁️" }, correct: 'a' },
    { q: "Which one is STORMY?", a: { txt: "Storm", icon: "⛈️" }, b: { txt: "Sun", icon: "☀️" }, correct: 'a' },
  ],
  simple_addition: [
    { q: "1 + 1 = ?", display: "1 + 1", a: { txt: "2", icon: "2️⃣" }, b: { txt: "3", icon: "3️⃣" }, correct: 'a', speakText: "One plus one equals two" },
    { q: "2 + 1 = ?", display: "2 + 1", a: { txt: "3", icon: "3️⃣" }, b: { txt: "4", icon: "4️⃣" }, correct: 'a', speakText: "Two plus one equals three" },
    { q: "1 + 2 = ?", display: "1 + 2", a: { txt: "3", icon: "3️⃣" }, b: { txt: "2", icon: "2️⃣" }, correct: 'a', speakText: "One plus two equals three" },
    { q: "2 + 2 = ?", display: "2 + 2", a: { txt: "4", icon: "4️⃣" }, b: { txt: "3", icon: "3️⃣" }, correct: 'a', speakText: "Two plus two equals four" },
    { q: "1 + 3 = ?", display: "1 + 3", a: { txt: "4", icon: "4️⃣" }, b: { txt: "5", icon: "5️⃣" }, correct: 'a', speakText: "One plus three equals four" },
    { q: "3 + 1 = ?", display: "3 + 1", a: { txt: "4", icon: "4️⃣" }, b: { txt: "3", icon: "3️⃣" }, correct: 'a', speakText: "Three plus one equals four" },
    { q: "2 + 3 = ?", display: "2 + 3", a: { txt: "5", icon: "5️⃣" }, b: { txt: "4", icon: "4️⃣" }, correct: 'a', speakText: "Two plus three equals five" },
    { q: "1 + 4 = ?", display: "1 + 4", a: { txt: "5", icon: "5️⃣" }, b: { txt: "6", icon: "6️⃣" }, correct: 'a', speakText: "One plus four equals five" },
    { q: "3 + 2 = ?", display: "3 + 2", a: { txt: "5", icon: "5️⃣" }, b: { txt: "4", icon: "4️⃣" }, correct: 'a', speakText: "Three plus two equals five" },
    { q: "1 + 1 = ?", display: "1 + 1", a: { txt: "2", icon: "2️⃣" }, b: { txt: "1", icon: "1️⃣" }, correct: 'a', speakText: "One plus one equals two" },
  ]
};

// Shuffle all questions in all modules when app loads
Object.keys(learningModules).forEach(key => {
  learningModules[key] = [...learningModules[key]].sort(() => Math.random() - 0.5);
});
